language: objective-c
xcode_project: Landmarks/LearningSwiftUI.xcodeproj # path to your xcodeproj folder
xcode_scheme: Landmarks/LearningSwiftUITests
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 11 Pro Max
